### ISSUE TITLE
Update UI of login page

### ISSUE THREAD

**Issue by shubhranshii** [jaygajera17/E-commerce-project-springBoot#68]
The ui of user login should be updated to match that of admin login.

<img width="1470" alt="Screenshot 2024-07-01 at 5 09 27 PM" src="https://github.com/jaygajera17/E-commerce-project-springBoot/assets/114684758/2e3a40b9-9b98-485a-a415-97f8410c30dc">
<img width="1470" alt="Screenshot 2024-07-01 at 5 15 48 PM" src="https://github.com/jaygajera17/E-commerce-project-springBoot/assets/114684758/73e55fe7-ec04-4d12-b285-c399117cb553">

**Comment by jaygajera17** [comment]
@shubhranshii You can work on this issue , apart from match  you can enhance UI as possible.
