### ISSUE TITLE
Refactor Dependency Injection in Controllers to Constructor Injection

### ISSUE THREAD

**Issue by Grad566** [jaygajera17/E-commerce-project-springBoot#74]
Hey!
I believe it's better to implement dependency injection in controller classes using constructors instead of field injection. I could use Lombok to simplify this, or I could do it manually by explicitly defining the constructors.
Can I work on it?

**Comment by Grad566** [comment]
Hi @NisargPipaliya!
Could you please reply to me?

**Comment by NisargPipaliya** [comment]
Hey @Grad566 
Sorry for late reply.
That's a great idea,
You can start working on the issue.
You have 14 days to complete the task, all the best 👍

**Comment by Grad566** [comment]
Hey!
I have completed the changes. Could you please check my pull request at the following link?
[Pull Request #75](https://github.com/jaygajera17/E-commerce-project-springBoot/pull/75)

**Comment by NisargPipaliya** [comment]
Great Work, @Grad566
