### ISSUE TITLE
Use Spring Security for Admin Role Management

### ISSUE THREAD

**Issue by Guhapriya01** [jaygajera17/E-commerce-project-springBoot#79]
Admin roles are currently managed in controllers. This should be refactored to use `Spring Security` for better security and maintainability. Implement `role-based access control` and move role checks to a `security configuration`.

**Comment by NisargPipaliya** [comment]
Are you willing to solve this issue?
@Guhapriya01

**Comment by Guhapriya01** [comment]
Yes, I'm willing to work on it. I'll refactor the admin role management using Spring Security.

**Comment by NisargPipaliya** [comment]
ok,
go on you have 14 days
@Guhapriya01

**Comment by Guhapriya01** [comment]
Thanks @NisargPipaliya! I'll start.
